format_version: 2
pipelines:
  Demo:
    group: Todo App
    materials:
      git-repo:
        git: https://github.com/nongpoo/gocd-pipeline-config.git
        branch: master
    stages:
      - first-stage:
          jobs:
            list:
              tasks:
                - exec:
                    command: ls
                    arguments:
                      - .