format_version: 2
pipelines:
  Demo:
    group: Todo-list
    materials:
      git-repo:
        git: https://github.com/nongpoo/gocd-pipeline-config.git
        branch: master
    stages:
      - first-stage:
          jobs:
            list:
              tasks:
                - exec:
                    command: ls
                    arguments:
                      - .
  Build:
    group: Todo-list
    materials:
      git-repo:
        git: https://github.com/nongpoo/vue-gotham-todo.git
        branch: master
    stages:
      - build:
          jobs:
            npm-install:
              tasks:
                - exec:
                    command: ./gotham-todo/build.sh
          